# Generated by Django 2.2.4 on 2019-09-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ddos_dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddos_data', models.CharField(max_length=500)),
                ('attack_result', models.CharField(max_length=500)),
            ],
        ),
    ]
